services:
  - type: web
    name: AQUA_MUSIC_BOT
    env: python
    python_Version: "3.11"
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "python main.py"
